### ISSUE TITLE
Option to have fullscreen mode active by default

### ISSUE THREAD

**Issue by keineahnungking** [ZXY101/mokuro-reader#18]
Currently when I'm opening a volume or reopening the browser on my Android device the reader defaults to have fullscreen mode off. I would like the option to have this behavior reserved and always default to fullscreen instead.

**Comment by ZXY101** [comment]
Just added a new "Open reader in fullscreen" setting.

**Comment by keineahnungking** [comment]
Thanks, that setting is great.

However on Android specifically I still have the issue that when going to another app and then reopening the browser where Mokuro Reader is running, the reader always reverts back to not being in fullscreen. If it's possible it would be great to always keep the fullscreen active. Maybe that is outside of the scope of this app and has to be solved with something like Tasker.

**Comment by ZXY101** [comment]
@keineahnungking Unfortunately you can't have full screen persist when switching between apps, at least not consistently.
I tried to re toggle fullscreen when the app is refocused and it sorta worked but browsers reject the full screen request if there is no user input so it fails every other time.
So tl;dr it's kinda impossible.

If you really find yourself needing to switch between apps constantly, what you can maybe do is enable the quick actions button, theres a fullscreen toggle there which is a lot more convenient to press.
