### ISSUE TITLE
Cannot import manga using Safari (macOS/iOS)

### ISSUE THREAD

**Issue by liveauvst** [ZXY101/mokuro-reader#19]
I am successfully able to import manga into mokuro reader via Firefox, but seem unable to do the same via Safari (both on macOS and iOS). This prevents me from reading manga on my iPhone which I did a lot using the old mokuro fork before it was deprecated recently.

Does `mokuro-reader` currently not support Safari?

**Comment by ZXY101** [comment]
Yeah the reader does not support Safari for a handful of reasons and never will.
You should still be able to use it on on your phone if you use another browser.

**Comment by liveauvst** [comment]
> You should still be able to use it on on your phone if you use another browser.

I'm not sure if this is the case yet on iOS. As of earlier this year, Apple opened up the App Store to allow 3rd party browser engines, but I have a feeling all the major browsers available on the iOS app store still utilize Safari/WebKit.

You answered my question though, so thank you.
