### ISSUE TITLE
Compress images taken for AnkiConnect

### ISSUE THREAD

**Issue by keineahnungking** [ZXY101/mokuro-reader#20]
Currently when I take a screenshot with Mokuro Reader for mining the resulting image is in .webp format and quite large (1 MB cropped and 8 MB uncropped). I'm worried that my Anki collection will become too large at that rate. When I crop the image in Anki it gets converted to jpeg and then has only a third of the filesize. Maybe it could be possible to save the images in jpeg in the first place? There could also be options to batch compress images in Anki but I don't know if that exists.

**Comment by ZXY101** [comment]
Are you reading an upscaled manga with very large files?
8mb uncropped seems excessive, seems like something that was upscaled and never appropriately downscaled.

That aside webp is a much better format, I intentionally convert it to webp so that the file size will be smaller. 

How are you cutting/converting it in anki? An uncompressed jpeg should be much larger than a lossless webp.

**Comment by keineahnungking** [comment]
I just used the crop function in AnkiDroid and that probably compresses it as well. Maybe I should look into compressing/downscaling the manga I upscaled.

**Comment by ZXY101** [comment]
Yeah you definitely don't want to use the fully upscaled version, the files are massive, they seem a bit *too* sharp and if it's way too big its also pretty jank in mokuro with the scanned text being too small.
If you're using chainner then its really easy to add a resize (factor) and compression.

My upscaling settings look like this
![image](https://github.com/ZXY101/mokuro-reader/assets/39561296/b4355b36-4d8e-4c5b-a398-0cef4c91bb91)
You upscale it, then scale it down and then save it as a webp with some compression

Quality is still much better than before but the file size isnt crazy.
Play with the settings to find results you're happy with, but you really don't want to be using the raw upscaled images.
