### ISSUE TITLE
Overscroll navigation activates while panning on PC

### ISSUE THREAD

**Issue by darren-moore** [ZXY101/mokuro-reader#4]
In Chromium, if you swipe left or right, the browser back/forward gesture activates while trying to pan around the page.
I found the following CSS prevents this:
`html, body { overscroll-behavior: contain; }`

I tested this by adding the lines to the html and body sections in the devtool inspector, but I'm not sure where to add this in the app's code.

**Comment by ZXY101** [comment]
Should be fixed now.
