### ISSUE TITLE
Some improvements 

### ISSUE THREAD

**Issue by Kalleo1** [ZXY101/mokuro-reader#5]
1. Be able to change the manga cover with an image of your choice.
2. Also display the covers from each volume when you click on the manga, instead of only showing the name and number of pages.
3. If the second option is implemented, having the ability to choose between grid or list mode for displaying volumes would also be good.
4. Have more control over the time spent reading
	- Implement a timer that allows you to start, stop and reset it.
	- Pause the timer if you switch tabs or lose window focus.
	- Option to display either only minutes or hours and minutes.

**Comment by ZXY101** [comment]
1. Considering
2/3. Will not be adding volume based/grid view for the volume page as it will clash with existing & planned functionality for that page.
4. The timer can now be paused/resumed, will look at redesigning with more functionality in the future.
