### ISSUE TITLE
Hidden text "Volume" gets included in the {cloze-suffix}

### ISSUE THREAD

**Issue by precondition** [ZXY101/mokuro-reader#7]
While mining words that appear at the end of speech bubbles, I noticed that the word "Volume" keeps getting added into the `Sentence` field of my Anki cards.

I noticed the same problem happened across different volumes of the same series I was reading (namely Shadow House [Upscaled]), so I searched for the word "Volume" in the HTML source of the reader and I found this `div`:
![offending div](https://github.com/ZXY101/mokuro-reader/assets/57645186/4effb31d-a908-4827-8335-ca681596a1fe)
I could confirm that this is what YomiChan was picking up by editing the contents of the tag and seeing my modifications appear on new cards I made.

<details>
<summary>Example of an affected card</summary>

![image](https://github.com/ZXY101/mokuro-reader/assets/57645186/1aeb44bf-39e4-47da-8d45-1b4996c599ab)

</details>

**Comment by ZXY101** [comment]
Yeah I've experienced this before, but it actually seems to be more an issue with Yomichan.
I managed to recreate this on another website, essentially yomichan is grabbing the text from the notification toast.

I'm not actually sure where yomichan is grabbing the text from in your case though, their shouldn't be any toast with the text "Volume" in the code base, so it might be grabbing the text from the settings menu? That seems to be the only place that text should be visible in the reader.

**Comment by walteranderson** [comment]
This looks to be related to sveltekit's accesibility feature "Announcing the page change", which is pretty undocumented but I found [this issue](https://github.com/sveltejs/kit/issues/307) that describes it. Doesn't seem like there's any way of hiding or removing it.

I wonder if there's some way of indicating to yomichan/tan where the sentence boundaries are more explicitly?

**Comment by ZXY101** [comment]
Closing for now, for the time being just adjust your yomitan/yomichan termination characters.
