### ISSUE TITLE
Unable to import on android tablet

### ISSUE THREAD

**Issue by jamesrender50** [ZXY101/mokuro-reader#8]
Unable to import files using either firefox or kiwi browser on Android 14.

- Couldn't drag and drop.
- Selecting 'choose directory' opens up file explorer-like apps but unable to select a directory.
- Unable to determine the requirements needed in order to use 'choose files'
[More troubleshooting I attempted](https://community.wanikani.com/t/mokuro-read-japanese-manga-with-selectable-text-inside-a-browser/60907/260?page=9)

I was able to use drag and drop / choose directory from windows 10.  Was unable to figure out what was necessary to use the 'choose files' option on windows as well.

**Comment by ZXY101** [comment]
I'll work on better instructions in the near future, but on mobile selecting directory is not supported.

The only way you can import the volumes on mobile is to select "choose files" then select the mokuro file and a zip of the images.
